# Defines the port where the config server is running
# Their external configuration
server:
    port: 9090

spring:
    cloud:
        config:
            server:
                git:
                  uri: https://github.com/edneyRoldao/microservices-config.git
                  search-paths: MASTER